name: Build Chrome Extension

on:
  push:
    tags:
      - '*'

jobs:

  build-extension:

    runs-on: ubuntu-latest
    env:
      RELEASE_NAME: chessdotcom-expanded-themes_${{ github.ref_name }}

    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Setup node 19.9
        uses: actions/setup-node@v3
        with:
          node-version: 19.9
      -
        name: Install npm packages
        run: npm install
      -
        name: Build extension
        run: |
          node --version
          npm --version
          npm run build
      -
        name: Zip and release
        run: |
          mv build/ ${RELEASE_NAME}/
          zip -r ${RELEASE_NAME}.zip ${RELEASE_NAME}/
          ls -l
